name: Build and deploy container app to Azure Web App - placesadmin-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Azure Container Registry
      uses: docker/login-action@v2
      with:
        registry: placesadmincr.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and push container image to ACR
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: placesadmincr.azurecr.io/placesadmin:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'production'

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'placesadmin-app'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_877DBDCFF6FB400180D966B202A14783 }}
        images: 'placesadmincr.azurecr.io/placesadmin:${{ github.sha }}'
